import React from "react"
import Button from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/J2LLnfBQi1MCjF2DREqdrD/nextjs-mcp?node-id=30%3A1791",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "action": figma.enum('Action', {
      //   "Default": "default",
      //   "Hover": "hover"
      // })
    },
    example: (props) => <Button label={/* TODO */} />,
  },
)
